// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2DzBFja8Ey7AfQtZwQw0VJfAQKINhDmE',
    appId: '1:1049044691812:web:c495f03d1d7c419128a871',
    messagingSenderId: '1049044691812',
    projectId: 'whats-up-bro',
    authDomain: 'whats-up-bro.firebaseapp.com',
    storageBucket: 'whats-up-bro.appspot.com',
    measurementId: 'G-MDJ0GLJ3EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxEj6IsRgoRAtL5EdL8peeUnsnUPK1TG8',
    appId: '1:1049044691812:android:e12da9029db1f5d628a871',
    messagingSenderId: '1049044691812',
    projectId: 'whats-up-bro',
    storageBucket: 'whats-up-bro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsBjIekuWOczQQ1aCVGFWF5yAqJ911yAA',
    appId: '1:1049044691812:ios:e1099f05449836a628a871',
    messagingSenderId: '1049044691812',
    projectId: 'whats-up-bro',
    storageBucket: 'whats-up-bro.appspot.com',
    iosClientId: '1049044691812-t5emq8q5cr6qp3ek0mc0054n1f51d46t.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsUpBroo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsBjIekuWOczQQ1aCVGFWF5yAqJ911yAA',
    appId: '1:1049044691812:ios:f2b182200caabd7128a871',
    messagingSenderId: '1049044691812',
    projectId: 'whats-up-bro',
    storageBucket: 'whats-up-bro.appspot.com',
    iosClientId: '1049044691812-fq90jra9er1ol3uq7t6jjk8ht5bpj2fu.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsUpBroo.RunnerTests',
  );
}
